services:
- docker

sudo: required
before_install:
  - ./install.sh docker_compose
  - docker-compose --version

language: python

script:
  - docker-compose build
  - docker-compose start
  - curl http://localhost/status
  - docker-compose stop
