services:
- docker

sudo: required
before_install:
  - ./install.sh docker_compose
  - ./install.sh meshblu_v2

language: python

script:
  - docker-compose start
  - curl http://localhost/status
  - docker-compose stop
