services:
- docker

sudo: required
before_install:
  - ./install.sh docker_compose
  - ./install.sh meshblu_v2

language: python

script:
  - sleep 20 # let meshblu start up
  - curl http://localhost/status
