version: '2'

services:
 redis:
   image: redis
   ports:
     - "6379:6379"

 mongo:
   image: mongo
   ports:
     - "27017:27017"

 meshblu-core:
   image: octoblu/meshblu-core-dispatcher:v20.1.2
   env_file: meshblu.env
   depends_on:
      - "redis"
      - "mongo"

 meshblu-http:
   image: octoblu/meshblu-core-protocol-adapter-http:v6.1.0
   env_file: meshblu.env
   depends_on:
     - "redis"
     - "mongo"
   ports:
     - "80:80"
   environment:
     - "PORT=80"

 meshblu-mqtt:
   image: octoblu/meshblu-core-protocol-adapter-mqtt:v2.1.4
   env_file: meshblu.env
   depends_on:
     - "redis"
     - "mongo"
   ports:
     - "1883:1883"
   environment:
     - "PORT=1883"

 meshblu-coap:
   image: octoblu/meshblu-core-protocol-adapter-coap:v2.1.1
   env_file: meshblu.env
   depends_on:
     - "redis"
     - "mongo"
   ports:
     - "5683:5683/udp"
   environment:
     - "PORT=5683"

 meshblu-webhook:
   image: octoblu/meshblu-core-worker-webhook:v3.4.1
   restart: on-failure:10
   env_file: meshblu.env
   depends_on:
     - "redis"
     - "mongo"

 meshblu-socketio:
   image: octoblu/meshblu-core-protocol-adapter-socket.io:v9.1.0
   restart: on-failure:10
   env_file: meshblu.env
   depends_on:
     - "redis"
     - "mongo"
   ports:
     - "9180:80"
   environment:
     - "PORT=80"

 meshblu-websocket:
   image: octoblu/meshblu-core-protocol-adapter-websocket:v4.0.1
   restart: on-failure:10
   env_file: meshblu.env
   depends_on:
     - "redis"
     - "mongo"
   ports:
     - "5000:80"
   environment:
     - "PORT=80"

networks:
 default:
   driver_opts:
      com.docker.network.enable_ipv6: "true"
